name: Android CI

on: [push, pull_request]

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, windows-latest, macOS-latest ]

    steps:
    - name: Check out
      uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: '11'
    - name: Create symlink to Android SDK without spaces
      if: runner.os == 'Windows'
      run: |
        $oldAndroidPath = $env:ANDROID_SDK_ROOT
        $sdk_root = "C:\Android"
        New-Item -Path $sdk_root -ItemType SymbolicLink -Value $oldAndroidPath
        echo "ANDROID_SDK_ROOT=$sdk_root" >> $env:GITHUB_ENV
        echo "ANDROID_HOME=$sdk_root" >> $env:GITHUB_ENV
    - name: Build with Gradle
      run: ./gradlew aR
    - name: Upload build artifact
      uses: actions/upload-artifact@v2
      with:
        name: ${{ matrix.os }}-artifact
        path: app/build/outputs/apk/release/app-release.apk
